name: riddance_env
version: 0.0.2
description: Automate Flutter maintenance chores.
topics:
  - devenv
  - riddance
  - codegen
  - template
  - build-runner

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: 1.9.0
  yaml: 3.1.2

dev_dependencies:
  lints: 3.0.0
